### PR TITLE
Modified quick use button

### PR DESCRIPTION
**Pull request by SergioCasCeb**
- Changed the quick-use button to a simpler, more obvious variation.
- Instead of utilizing an icon that implies import, the button now has the simple text of "use"

### CODE REVIEW

**Comment by egekorkan** [comment]
@danielpeintner @mkovatsc do you prefer this more direct "USE" button compared to the icon?

**Comment by egekorkan** [comment]
@danielpeintner now we use load as it also makes more sense to me. 
The failing test is being addressed in another PR. 

@SergioCasCeb there should be no changes to the copyright years in this PR. Can you rebase it?

**Comment by SergioCasCeb** [comment]
What exactly do you mean with the copying years?

Also should the button, when opening the example card, also say load instead of apply to avoid any confusion between the functionality of each button?

**Comment by egekorkan** [comment]
> Also should the button, when opening the example card, also say load instead of apply to avoid any confusion between the functionality of each button?

I hadn't seen that sadly. I think that row with two buttons can either be removed (not sure yet). For now, the "apply" button should also say load.

**Comment by egekorkan** [comment]
> @egekorkan what exactly do you mean with the copying years?

Currently, this PR has 97 file changes but they are due to copyright years (see screenshot below) changing.

image

It even shows the change again (not sure why) since https://github.com/eclipse-thingweb/playground/pull/546 has already did the correction. We are now using the creation date instead of the current year.

**Comment by SergioCasCeb** [comment]
Ok, I will change the text of the other Button. 

And rebase the branch to fix the copyright texts.

**Comment by SergioCasCeb** [comment]
@egekorkan , I fixed the button name and some styling issues. Still, regarding the copyright issue, I got a bit confused because I checked some other packages in the master branch from the eclipse-thingweb repository and they also have different dates.

By date of creation do you mean the creation of the individual package or the project itself?

Also I don't think rebasing will help me do that, but if you want, with the search function in VSCode I can set everything again to the correct date, or should that be done in another PR on itself?

**Comment by egekorkan** [comment]
Changing the base branch twice solved the copyright year issues. Merging

**Pull request merged**
